apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: app-flask
  name: app-flask
spec:
  ports:
  - name: "56733"
    port: 56733
    targetPort: 8080
  selector:
    io.kompose.service: app-flask
status:
  loadBalancer: {}
