apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: app-flask
  name: app-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-flask
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: app-flask
    spec:
      containers:
      - args:
        - spark-submit
        - app.py
        image: weropanika/app-flask
        imagePullPolicy: ""
        name: app-flask
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
