{
 "title": "Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Title length ditribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "distributions",
     "select": [
      [
       { "params": [ "title_len" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Post score distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "distributions",
     "select": [
      [
       { "params": [ "post_score" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Comments count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "counts",
     "select": [
      [
       { "params": [ "comment_count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Post count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "counts",
     "select": [
      [
       { "params": [ "post_count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Submission fetch times distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "time_exe",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Submission fetch times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "time_exe",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}